version: '3'

services:

  mysql:
    image: mysql:5.7.20
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: example
      MYSQL_PASSWORD: example
      MYSQL_DATABASE: db_counter
    volumes:
      - db_counter:/var/lib/mysql

volumes:
  db_counter:
    external: true
